[package]
name = "mm-eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
logos = "0.13"
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"
typed-arena = "2.0"
